version: "3.7"

services:
  web:
    build:
      context: ./services/web
    image: dirac1234/hammergen_web
    volumes:
      - static_volume:/app/static
    restart: always
    expose:
      - 5000
    env_file:
      - ./.env.dev
      - .env.secrets.staging
  nginx:
    build: ./services/nginx
    image: dirac1234/hammergen_nginx
    volumes:
      - static_volume:/app/static
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: